### ISSUE TITLE
Merge harmonized landsat sentinel data (HLS)

### ISSUE THREAD

**Issue by khufkens** [khufkens/cropmonitor#2]
Tiles not yet available for 2017

**Comment by mmann1123** [comment]
having some trouble with an ubuntu install:

install_github("khufkens/cropmonitor")


** preparing package for lazy loading
Error in df$userfield : object of type 'closure' is not subsettable
Error : unable to load R code in package ‘cropmonitor’
ERROR: lazy loading failed for package ‘cropmonitor’
* removing ‘/home/mmann1123/R/x86_64-pc-linux-gnu-library/3.4/cropmonitor’
Installation failed: Command failed (1)

Any ideas?

**Comment by khufkens** [comment]
explicit plotting command in the location validation function (at the end, now removed).
